import { Inter } from "next/font/google";
import "./globals.css";
import { Header, TopLoader } from "@/components";
import ReduxProvider from "./ReduxProvider";
import MobileNavigation from "@/components/header/MobileNavigation";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          <Header />
          <TopLoader />
          <Toaster />
          <div className="block xl:hidden">
            <MobileNavigation />
          </div>
          <div className="container-fluid mx-auto">{children}</div>
        </ReduxProvider>
      </body>
    </html>
  );
}
